use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

target 'SZWebViewBridge_Example' do
  pod 'SZWebViewBridge', :path => '../'

  target 'SZWebViewBridge_Tests' do
    inherit! :search_paths

    
  end
end
